#!/usr/bin/env bash
# Write a Bash script that pings an IP address passed as an argument.

# Check if the number of arguments is not equal to 1
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Extract the IP address from the argument
ip_address=$1

# Ping the IP address 5 times
ping -c 5 $ip_address

# Exit with the status code of the last command (ping)
exit $?